### ISSUE TITLE
esc clous

### ISSUE THREAD

**Issue by Frkgkc67** [Project-Sloth/ps-hud#11]
hello "I" I close the pop-up menu with the ESC key and its headlight stays in the middle of the screen and prevents me from moving

**Comment by Frkgkc67** [comment]
![image](https://user-images.githubusercontent.com/83988653/172157211-730f1ab4-a545-457a-ad0d-4efb6ac887ec.png)
What could be the cause of this error?

**Comment by pushkart2** [comment]
Please redownload.. also not an issue with script. Also ask these questions in discord
