### ISSUE TITLE
Request: Client side customization

### ISSUE THREAD

**Issue by katsacca** [Project-Sloth/ps-hud#15]
Having the ability to enable each client to select the hud position and the generic sizing that they want would be amazing. if we really want to make it even sweeter would allow admins to toggle each field to enable for client modification, populating the same component with the client side fields that admins would see, but slimmed down.

perhaps saving those few fields in the player table, or even its own, based off a license id would mean that different CID's wouldn't have to set up the positioning for each character. also, it'd be a smaller table. If they don't have it modified, default to the server's default settings.

**Comment by MonkeyWhisper** [comment]
Not taking any new features right now.
