### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by GhzGarage** [Project-Sloth/ps-hud#2]
Great job on the release but I’m noticing that it’s missing the GPL licensing here from qb-hud but instead now has a copyright claim. If you’d prefer to actually copyright the resource then I’d suggest re-writing the client/server/config entirely so it’ll be it’s own resource and not have to adhere to the GPL licensing which requires any re-releases be licensed under the same. If you could add that I’d appreciate it, thanks!

**Comment by GhzGarage** [comment]
Just got more clarity https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-hud/blob/main/LICENSE

It is GPL?

**Comment by GhzGarage** [comment]
Yes

**Comment by MonkeyWhisper** [comment]
> Yes

Okay, so can I close this issue?

**Comment by GhzGarage** [comment]
Yes thank you

**Comment by MonkeyWhisper** [comment]
Appreciate it
