### ISSUE TITLE
Buff icons not showing after re-log

### ISSUE THREAD

**Issue by DannysRP** [Project-Sloth/ps-hud#21]
If you have an active buff and leave the server then join back the buff icon will be an exclamation point instead of showing the respective icon.

EDIT: Buffs also transfer between players if you do /logout and switch characters or logout via housing or apartments. They do not transfer if you close out of the game completely and choose another character.

**Comment by S1lentcodes** [comment]
Yep, simple fix should be in the next update. Thanks for your patience I know you been waiting since you posted this issue in the last repo.

**Comment by DannysRP** [comment]
Thanks for the quick response Silent. Although that icons not popping up is a newer issue for me. I don't recall that happening on the old version. Other than that great work

**Comment by DannysRP** [comment]
Also noticed after re logging and selecting another character it breaks the HUD with a metadata error
