### ISSUE TITLE
[BUG] Support widescreen displays

### ISSUE THREAD

**Issue by bedar89** [Project-Sloth/ps-hud#22]
I'm running on 3440 x 1440 and the border never matches the minimap.
As suggested in discord, I've changed the savezone in my display settings, but I'm never able to match the border with the minimap.
So I think support for widescreens is needed.

![IU3Akpz](https://user-images.githubusercontent.com/2621954/174281751-d0b4d25e-29ab-41a9-96f5-060ac3cb9ffe.png)

**Comment by S1lentcodes** [comment]
Yep will get this done in the coming update
