### ISSUE TITLE
[issue]Set the $ in to € when you do /bank or /cash not working

### ISSUE THREAD

**Issue by Zilockegaming** [Project-Sloth/ps-hud#23]
Hi there i have a a server that is lockated in europe and i want to chainge the $ to € when the player is executing the command/cash or /bank i did this in the monney hud file but it is still on $ when i do/bank or /cash how can i fix this?

**Comment by S1lentcodes** [comment]
Hey thanks for being this issue up. I already have this feature as a config option in the dev branch. You could start using the code from that branch, though keep in mind stuff may not be working in the dev branch as its not as stable as main. I should be merging this branch into the main branch soon.

**Comment by Zilockegaming** [comment]
doe you have the kink to it?

**Comment by S1lentcodes** [comment]
Yep right here: https://github.com/Project-Sloth/ps-hud/tree/dev
