### ISSUE TITLE
New hud element - Blood value (bleeding)

### ISSUE THREAD

**Issue by ButtCheek** [Project-Sloth/ps-hud#28]
Hi, 

I wanted to suggest adding blood level as another hud element. 

The features I would suggest:
 
1. Visual representation of when the player is bleeding. Have a pulsating effect added to the element. 
2. To add to the pulsating effect and provide clarity. I would suggest adding different colours for the different stages of the bleed. 
3. Having the 0-100%, similar to health, food, or water. 
4. Adding a variable which would control the 0-100% of the new element. 

Some of the reasons why I think this feature would be a good addition:

1. It would provide a visual representation of when the player is bleeding.
2. Would allow to incorporate new features to bleeding.

Personally, I want to expand the health system in the game by adding blood value. Which would be used by some other new features such as addiction and drugs as well as reworking the bleed system and how bleeding affects health.

**Comment by S1lentcodes** [comment]
Yeah I like the idea, but I think we would really need to iron out a lot of the detail before this could start being developed. We would need a list of stages of bleeding. Do we just have general bleeding or have it per major body part? Would we need special badges/items to stop certain bleeding? Would major internal bleeding or similar be only treatable via surgery? Once we iron out what is each component in the feature then that would help me better understand the proposed feature.

**Comment by ButtCheek** [comment]
I've been trying to keep it as close to QBCore as possible. I'm trying to leave the bleeding the same way, 4 stages, general bleeding instead of body parts. The only real difference is when does the bleeding affect the health. I've been playing around with it and trying to find the correct balance for now. 

Currently, I have it set as follows: 
Bleed stage one lasts for 5 ticks and each tick lowers the blood level by 1. I do think either blood ticks or the amount should be increased. 
Blood stage two lasts for 10 ticks and each tick lowers the blood level by 2 and the health by 2 *  Config.BleedTickDamage (from qb-ambulancejob)
Blood stage three is the same as blood stage two except values for blood level and health are 3 instead of two. 
Blood stage four again repeats from stage three except 3 is now 4. 

I think I'm creating a good base, but I do like your idea of linking bleeding to specific body parts and even extending it into internal bleeding. However, I think with the current style of the hud it might be a bit difficult to project that to a player. Maybe something along the lines of a project zombies health UI would work out.

Example: https://i.imgur.com/uXP1GZY.png

But even with the expansion, I would imagine blood having a set level that can be depleted and replenished. The only difference the bleeding from specific body parts would do is add a source which another player or the wounded player could explore and take care of. Which would greatly improve the current medical system. 

If you want I can send you the changes once I complete them.

**Comment by MonkeyWhisper** [comment]
There is only one bleeding, and that is bleeding. We are not going to do core changes to implement this. 

QBUS had this originally on their hud.

**Comment by ButtCheek** [comment]
> There is only one bleeding, and that is bleeding. We are not going to do core changes to implement this.
> 
> QBUS had this originally on their hud.

No core changes are needed to implement this element, but you also don't have to implement it. 

Currently, a 3 or 4 stage bleed system is implemented in qbcore's ambulancejob. Not sure if it's 3 or 4 by default, as I made some changes. 
In-game they are represented by minor/bleeding/major bleeding popping as notifications on the player's screen. 

The only thing I personally asked for is the possibility to change the value of the element from a 0 to a 100 and I'm pretty sure that can be implemented with an export. At the end of the post I explain why it could be beneficial to a default qbcores system.

The way I would implement it is to make a UI element that by default has a value of 100 and since default qbcore doesn't change the value, the element would always appear full. The only thing affecting it would be the stages of the bleed which is already provided by qbcore. I'd simply make 3-4 stages for each bleed stage and give them varying effects. This would allow anyone to tackle the element as they want. 
For example they would be able to say that a stage 3 bleed changes the bleed value to 30 and apply the stage 3 bleed effect. Stage 2 could be 50 with stage 2 bleed effect. 
Again, just to highlight, neither of the examples above would need any changes to the qbcore, they would however allow for more versatile usage.

**Comment by MonkeyWhisper** [comment]
You're correct, there are 4 bleed states. Little, normal, lot and big bleed. 

Seems like I'm not keeping up with the times. 

Okay, I like this idea. 

Let's keep it open
