### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by zf-development** [Project-Sloth/ps-hud#3]
Hi. Using ps-hud the code like notifications are using locales but the menu etc are not / i haven't found them.

As this, I would like to know how I can translate the interface.

**Comment by MonkeyWhisper** [comment]
We won't be doing locales anytime soon.

**Comment by MonkeyWhisper** [comment]
Locales will be coming soon

**Comment by S1lentcodes** [comment]
Yep locales are done in the dev branch. So if your server needs it you can start using it, though keep in mind dev branch may have breaking changes.
