### ISSUE TITLE
Can't Toggle speedometer,fuel and seatbelt hud

### ISSUE THREAD

**Issue by b1naryerr0r** [Project-Sloth/ps-hud#30]
Hi guys!, i need to hide the fuel, seatbelt and speedometer hud, but i can't find the option to do that, please help!, i've another speedometer so i want to disable the ps-hud speedo

**Comment by Mac-Womack** [comment]
@S1lentcodes  has that been released yet if so where do i find it

**Comment by b1naryerr0r** [comment]
Hi guys!, any update for this ?
