### ISSUE TITLE
fix resolution

### ISSUE THREAD

**Issue by FL-OKI** [Project-Sloth/ps-hud#32]
ps-hud not support all resolution
i have problrm with different resolution like minimap border  and fuel and speed hud

I don't have these problems in qb-hud

**Comment by S1lentcodes** [comment]
@FL-OKI Thanks for the issue. What resolution are you on so I can get this fixed? I need a ###x### for example 1080x720.

**Comment by FL-OKI** [comment]
1360X768
1280x720
it's good thing if hud support all resolution 
like qb-hud 
and thanks for help

**Comment by MonkeyWhisper** [comment]
You need to adjust your safe zone settings
