### ISSUE TITLE
Metadata index value error

### ISSUE THREAD

**Issue by Wafflzdev** [Project-Sloth/ps-hud#39]
![image](https://user-images.githubusercontent.com/96218191/182750176-15f4f450-f1b1-40e0-955c-df436da0e94d.png)

This issue is due to some scripts setting a PlayerLoggedInState to "true" too soon.  Players need to look thru their scripts for any client side events that set the state to true too soon and adjust

**Comment by ADRNALN** [comment]
Did you find the root cause for your issue? I'm still trying to figure out whats causing it on my end

**Comment by MonkeyWhisper** [comment]
Not for support. Join Discord.
