### ISSUE TITLE
Compass staying On even disabled + 3 options not saving

### ISSUE THREAD

**Issue by TonybynMp4** [Project-Sloth/ps-hud#4]
![image](https://user-images.githubusercontent.com/97451137/172026547-6934d167-1b3f-49af-a9f4-89a405636fc4.png)

While on foot,

with the compass disabled but the compass only in vehicle disabled
the compass shows,

with compass disabled and only in vehicle
the compass doesn't shows,

While in a vehicle,
with the compass disabled but the compass only in vehicle disabled and with compass disabled and only in vehicle
the compass doesn't show

Also
![image](https://user-images.githubusercontent.com/97451137/172027331-05bee38c-3974-4536-97a4-7593ae714f96.png)
those 3 seem to reset to checked everytime i restart the script

**Comment by MonkeyWhisper** [comment]
> While on foot,
> 
> with the compass disabled but the compass only in vehicle disabled the compass shows,

While on foot,

with the compass disabled but the compass only in vehicle disabled
the compass shows,

The compass does not show. 
![image](https://user-images.githubusercontent.com/82112471/172120107-bf7bfe26-e794-4ddf-96cf-a4a351e5d72d.png)

those 3 seem to reset to checked everytime i restart the script
