### ISSUE TITLE
minimap.gfx not up to date

### ISSUE THREAD

**Issue by TonybynMp4** [Project-Sloth/ps-hud#5]
same problem as qb-hud
See this issue : https://github.com/qbcore-framework/qb-hud/issues/126
TL;DR : blips after b2060 are replaced by a dot because the minimap.gfx doesn't have those blips

**Comment by MonkeyWhisper** [comment]
Show screenshot of what happens with the blips.

**Comment by MonkeyWhisper** [comment]
> same problem as qb-hud See this issue : [qbcore-framework/qb-hud#126](https://github.com/qbcore-framework/qb-hud/issues/126) TL;DR : blips after b2060 are replaced by a dot because the minimap.gfx doesn't have those blips

Show screenshot of what happens with the blips.

**Comment by MonkeyWhisper** [comment]
Issue confirmed.

![image](https://user-images.githubusercontent.com/82112471/172121228-1d823c32-6f05-4e56-939e-c63a29a6f91e.png)

**Comment by pushkart2** [comment]
minimap.gfx is just downloaded directly through github or open source platforms. If someone knows, they can make the changes. Not a part of the hud issue right?

**Comment by TonybynMp4** [comment]
> minimap.gfx is just downloaded directly through github or open source platforms. 

i have no idea wtf that's suppose to mean

>If someone knows, they can make the changes. Not a part of the hud issue right?

It's an issue related to this repo, so it is an hud issue.
And yes someone could fix it, that's why i made the issue, so people could see that bug exists, 
Since the problem was carried from qb-hud i think maybe loljoshie either knows how to fix it or knows who can.

**Comment by MonkeyWhisper** [comment]
We won't be fixing this. It really is not a hud issue, we can simple just remove it and have it default.
