### ISSUE TITLE
Minimap hide issue.

### ISSUE THREAD

**Issue by HydraTownRP** [Project-Sloth/ps-hud#6]
After checking "Show Minimap only in Vehicle" and when player is not in vehicle,

Player is still able to see minimap.

![image](https://user-images.githubusercontent.com/76074105/172035993-bef37ac9-cf5f-4d8e-a1dd-634c5619690e.png)

**Comment by MonkeyWhisper** [comment]
This is not an issue. 

![image](https://user-images.githubusercontent.com/82112471/172119648-18fb1e19-f200-4c0f-9c40-d3c089694db1.png)

**Comment by MonkeyWhisper** [comment]
> After checking "Show Minimap only in Vehicle" and when player is not in vehicle,
> 
> Player is still able to see minimap.
> 
> ![image](https://user-images.githubusercontent.com/76074105/172035993-bef37ac9-cf5f-4d8e-a1dd-634c5619690e.png)

This is not an issue.

![image](https://user-images.githubusercontent.com/82112471/172119737-1692f99f-aba3-41ff-88aa-6a69d671c29f.png)
