### ISSUE TITLE
4k monitors not working correctly

### ISSUE THREAD

**Issue by skellykat** [Project-Sloth/ps-hud#61]
Hi i was trying this on my  3840 x 2160 monitor an for some reason it does this
![image](https://user-images.githubusercontent.com/47672755/202898844-f67503ab-897c-4740-a8e4-faf290f0a9ac.png)

**Comment by OfficialRDB** [comment]
Same here!

**Comment by MonkeyWhisper** [comment]
Adjust your FiveM safe zones

**Comment by Steviithetv** [comment]
How to adjust it?
