### ISSUE TITLE
/logout issue

### ISSUE THREAD

**Issue by Annalouu** [Project-Sloth/ps-hud#67]
To fix this issue Got to line 894

and add these lines above it and it should all look like this:

PlayerData = QBCore.Functions.GetPlayerData()
            if PlayerData == nil then return end
            playerDead = IsEntityDead(player) or PlayerData.metadata["inlaststand"] or PlayerData.metadata["isdead"] or false
            parachute = GetPedParachuteState(player)

**Comment by MonkeyWhisper** [comment]
> To fix this issue Got to line 894
> 
> and add these lines above it and it should all look like this:
> 
> PlayerData = QBCore.Functions.GetPlayerData() if PlayerData == nil then return end playerDead = IsEntityDead(player) or PlayerData.metadata["inlaststand"] or PlayerData.metadata["isdead"] or false parachute = GetPedParachuteState(player)

Send a PR for this please
