### ISSUE TITLE
[SUGGESTION] Media Query for 2560x1080 Monitors

### ISSUE THREAD

**Issue by ChristianBDev** [Project-Sloth/ps-hud#72]
I have included a media query for the 2560x1080 monitors

-- map-border-hud
@media (width: 2560px) and (height: 1080px) {
    .square {
        left: -0.25vw !important;
        bottom: -1.8vh !important;
    }
    .circle {
        left: 0.15vw !important;
        width: 27.6vh !important;
        bottom: -1vh !important;
    }
}

--particle-circle-ring
@media (width: 2560px) and (height: 1080px) {
    .vehicle-number {
        font-size: 1.7vh !important;
    }
    .vehicle-text {
        font-size: 0.9vh !important;
    }
}

-- Vehicle Hud
@media (width: 2560px) and (height: 1080px) {
    .responsive.svelte-18lolzz {
        margin-left: 33.5vh !important;
        transform: scale(1.3);
        bottom: 7.2vh !important;
    }
    #speedometer.svelte-18lolzz {
        position: relative;
        left: 0vw !important;
    }
    #fuelgauge.svelte-18lolzz {
        position: relative;
        left: 2vw !important;
        bottom: 5.95vh !important;
    }
    #altitudegauge.svelte-18lolzz {
        position: relative;
        left: 4vw !important;
    }
    #seatbelt.svelte-18lolzz {
        position: relative;
        left: 4.1vw !important;
        bottom: 8.5vh !important;
    }
    #seatbeltAltitude.svelte-18lolzz {
        position: relative;
        left: 2.8vw !important;
        bottom: 12vh !important;
    }
}

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-hud/pull/73
