### ISSUE TITLE
Config Update + pt.lua

### ISSUE THREAD

**Issue by NamelessN3K0** [Project-Sloth/ps-hud#79]
I saw you took the qb-hud config, one thing got left out:
![image](https://user-images.githubusercontent.com/73558483/228896092-224608b5-8f03-4da5-9d8e-c5b6c73a729d.png)
For non programes who want to change that may cause some confusion as vehicle hud text is not defined on the CSS but rather on the "index.js", a simple CTRL+F for "MPH" will locate the text field.

Also there were some PT lines missing on the locales, here is the complete version:

[pt.lua.txt](https://github.com/Project-Sloth/ps-hud/files/11113712/pt.lua.txt)

**Comment by MonkeyWhisper** [comment]
For non-programmers they can learn to do it themself.
